name: Deploy Portfolio Site to Heroku

on:
    push:
        branches:
            - main # Trigger deployment on pushes to main branch
    workflow_dispatch: # Trigger manual deployments

jobs:
    build-deploy-backend:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout Repository
              uses: actions/checkout@v3

            - name: Deploy to Heroku
              uses: akhileshns/heroku-deploy@v3.13.15 # Heroku deployment library
              with:
                  branch: main
                  heroku_api_key: ${{secrets.HEROKU_API_KEY}}
                  heroku_app_name: "ajgiii-portfolio-site"
                  heroku_email: ${{ secrets.HEROKU_EMAIL }}
              env: # Environment variables with HD prefix for Heroku
                  HD_AWS_REGION: ${{ secrets.AWS_REGION }}
                  HD_AWS_ACCESS_KEY: ${{ secrets.AWS_ACCESS_KEY }}
                  HD_AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
                  HD_RECAPTCHA_URL: ${{ secrets.GOOGLE_RECAPTCHA_URL }}
                  HD_RECAPTCHA_SITE_KEY: ${{ secrets.GOOGLE_RECAPTCHA_SITE_KEY }}
                  HD_RECAPTCHA_SECRET_KEY: ${{ secrets.GOOGLE_RECAPTCHA_SECRET_KEY }}

    build-deploy-frontend:
        runs-on: ubuntu-latest
        needs: build-deploy-backend

        steps:
            - name: Checkout Repository
              uses: actions/checkout@v3

              # Set up Node.js for frontend
            - name: Set up Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: "20"

            - name: Install Dependencies and Build
              run: npm run frontend:prod

            - name: Configure Git
              run: |
                  git config --global user.name "angelogentileiii"
                  git config --global user.email ${{ secrets.CONTACT_FORM_RECIPIENT }}

            # Deploy to GitHub Pages
            - name: Deploy to GitHub Pages
              uses: peaceiris/actions-gh-pages@v3
              with:
                  github_token: ${{ secrets.GH_TOKEN }}
                  publish_dir: ./client/dist
              env:
                  VITE_SITE_URL: ${{ secrets.SITE_URL }}
                  VITE_AWS_REGION: ${{ secrets.AWS_REGION }}
                  VITE_AWS_ACCESS_KEY: ${{ secrets.AWS_ACCESS_KEY }}
                  VITE_AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
                  VITE_CONTACT_FORM_SENDER: ${{ secrets.CONTACT_FORM_SENDER }}
                  VITE_CONTACT_FORM_RECIPIENT: ${{ secrets.CONTACT_FORM_RECIPIENT }}
                  VITE_RECAPTCHA_URL: ${{ secrets.GOOGLE_RECAPTCHA_URL }}
                  VITE_RECAPTCHA_SITE_KEY: ${{ secrets.GOOGLE_RECAPTCHA_SITE_KEY }}
                  VITE_RECAPTCHA_SECRET_KEY: ${{ secrets.GOOGLE_RECAPTCHA_SECRET_KEY }}
