name: Deploy to GitHub Pages

on:
    push:
        branches:
            - main
            - gh-pages
    workflow_dispatch:

jobs:
    deploy:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout repository
              uses: actions/checkout@v2

            - name: Set Git identity
              run: |
                  git config --global user.email "angelo.john.gentile@gmail.com"
                  git config --global user.name "Angelo Gentile III"

            - name: Set up Node.js
              uses: actions/setup-node@v2
              with:
                  node-version: "14"

            - name: Install Dependencies
              run: npm install

            - name: Build application
              env:
                  GITHUB_TOKEN: ${{ secrets.GH_TOKEN }} # GitHub token for pushing to the repo
                  AWS_ACCESS_KEY: ${{ secrets.AWS_ACCESS_KEY }}
                  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY}}
              run: |
                  npm run predeploy # command to build application

            - name: Deploy to Github Pages
              run: |
                  npm run deploy # command to deploy application
